name: Flip Pull Request
on:
  pull_request:
    branches:
      - '**' # This matches all branches
env:
  BRANCH_NAME: ${{ github.base_ref }}
jobs:
  optimize_ci:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - name: Optimize CI
        id: check_skip
        uses: withgraphite/graphite-ci-action@main
        with:
          graphite_token: 'FSLXl6gCqdKjeJ4Miay0NOQPp86rMazHXm1W6IY3SCuDAzfFayc4VfVv3tjR'

  Pull-Request-Action:
    needs: optimize_ci
    if: needs.optimize_ci.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Use pnpm v9
        uses: pnpm/action-setup@v3
        with:
          version: 9.14.2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          cd apps/loco-web
          touch .env
          if [ "${{ env.BRANCH_NAME }}" = "main" ]; then
            echo "${{ secrets.PRODUCTION_ENV }}" > .env
          else
            echo "${{ secrets.STAGING_ENV }}" > .env
          fi
          pnpm install --frozen-lockfile

      - name: Build the code
        run: |
          cd apps/loco-web
          pnpm build
        env:
          CI: true
